version: "3.8"

networks: 
  default:
    name: pdocker_base-bridge
    external: true

services: 
########Projects##############
    industrious-api:
        build:
          context: ./industrious-api
        volumes:
        - ${APP_CODE_PATH_HOST}/Outsource/CQGG/JOB/industrious-api:/workspace
        tty: true
        expose:
        - "9501"         
    magento:
        build:
          context: ./magento
        tty: true
        entrypoint: bash
        expose:
        - "9000"     
        ports:
        - "2201:22"
        - "8001:8001"
        networks:
          default:
            aliases:
              - magento.cqggedm.local
    wordpress-blog:
        build:
          context: ./wordpress-blog
        tty: true  
        ports:
        - "680:80"
        - "6443:443"
        - "63306:3306"
    ecas:
        build:
          context: ./ecas
        tty: true
        entrypoint: bash
        expose:
        - "9000"     
        ports:
        - "2202:22"
        - "8002:80"
        networks:
          default:
            aliases:
              - ecas.local                